### PR TITLE
compatibility

### PR DESCRIPTION
**Pull request by ryanburnette**
- add compatibility with bundlers (module.exports)
- define ajquery as an object on window if $/$$ are already defined

### CODE REVIEW

**Comment by ryanburnette** [comment]
I removed the `window.ajquery` part.

**Comment by ryanburnette** [comment]
You need to merge that bugfix either way.

**Comment by ryanburnette** [comment]
```js
function $(sel,el){return(el||document).querySelector(sel)}function $$(sel,el){return(el||document).querySelectorAll(sel)}
```

```js
(function(){function $(sel,el){return(el||document).querySelector(sel)}function $$(sel,el){return(el||document).querySelectorAll(sel)}if(typeof module!=="undefined"&&typeof module.exports!=="undefined"){module.exports.$=$;module.exports.$$=$$}else if(window){window.$=$;window.$$=$$}})();
```

... the bloat.

**Comment by ryanburnette** [comment]
Ohhh the bloat

```bash
ryan@ryan-mbp ~/D/g/r/ajquery.js (main)> du ajquery.*
8	ajquery.js
8	ajquery.min.js
8	ajquery.pr.min.js
```

**Comment by ryanburnette** [comment]
Closing per our discussion. But note https://github.com/coolaj86/ajquery.js/pull/3/commits/4d21f282d7772024d29778931dc586def9fd0dbb so you can fix that.

**Comment by coolaj86** [comment]
uglify-js issue fixed via 589fe80

Thanks for pointing that out.

**Pull request closed without merging**
