### PR TITLE
Why not minify it

### PR DESCRIPTION
**Pull request by Electogenius**
(this wasn't tested so judging by my skills it probably doesn't work)

### CODE REVIEW

**Comment by coolaj86** [comment]
Primarily because a TCP packet is 1500 bytes, meaning that sending less data typically isn’t any faster.

But why not? Let’s do it!

#Over9000 #ToTheMoon!

**Comment by coolaj86** [comment]
However, I’d recommend instead adding the minification process to the package.json `pre-publish` So that it automatically builds and gets included in the npm publish.

(and so we don’t junk up the source code with build files 😉)

```bash
npx uglify-js -o ajquery.min.js ajquery.js
```

Something like that, I think ^^.

**Comment by Electogenius** [comment]
Oh, cool

In that case you could just uh, not change anything and close this PR

But thanks for letting me know about the pre-publish thingy, I’ll remember to use it if I can

Also thanks for giving me an excuse to not minify js I make hehe

**Comment by coolaj86** [comment]
Hmm... looks like pre-publish doesn't do you any good when services like unpkg go down unexpectedly and stuff starts breaking... 😢

**Comment by coolaj86** [comment]
Update on this: We minify much harder now, see #12.

Also, there's been a big update and the new, bigger, badder files are available pre-optimized for bundling:
- https://unpkg.com/ajquery@3.0.3/ajquery.min.js
- https://unpkg.com/ajquery@3.0.3/ajquery.min.cjs
- https://unpkg.com/ajquery@3.0.3/ajquery.min.mjs

**Pull request closed without merging**
